require('globals')
vim.cmd('luafile '..CONFIG_PATH..'/settings.lua')
require('settings')
require('plugins')
require('utils')
require('n-autocommands')
require('keymappings')
require("n-themes")
require('n-nvimtree') -- This plugin must be required somewhere before colorscheme.  Placing it after will break navigation keymappings
require('colorscheme') -- This plugin must be required somewhere after nvimtree. Placing it before will break navigation keymappings
require('n-galaxyline')
--require('nvim-comment')
require('n-nvim-compe')
require('n-barbar')
require('n-dashboard')
require('n-telescope')
require('n-gitsigns')
require('n-treesitter')
require('n-matchup')
require('n-autopairs')
require('n-rnvimr')
require('folke-which-key')
require('n-lsprooter')
require('n-lspsaga-nvim')
require('n-floaterm')

-- extras
if O.extras then
    require('n-numb-nvim')
--    require('dial')
    require('n-hop')
    require('n-colorizer')
--    require('n-symbols-outline')
end



-- TODO is there a way to do this without vimscript
--vim.cmd('source '..CONFIG_PATH..'/vimscript/functions.vim')
-- LSP
require('lsp')
require('lsp.angular-ls')
require('lsp.bash-ls')
require('lsp.clangd')
require('lsp.css-ls')
require('lsp.dart-ls')
require('lsp.docker-ls')
require('lsp.efm-general-ls')
require('lsp.elm-ls')
require('lsp.emmet-ls')
require('lsp.graphql-ls')
require('lsp.go-ls')
require('lsp.html-ls')
require('lsp.json-ls')
require('lsp.js-ts-ls')
require('lsp.kotlin-ls')
require('lsp.latex-ls')
require('lsp.lua-ls')
require('lsp.php-ls')
require('lsp.python-ls')
require('lsp.ruby-ls')
require('lsp.rust-ls')
require('lsp.svelte-ls')
require('lsp.terraform-ls')
-- require('lsp.tailwindcss-ls')
require('lsp.vim-ls')
require('lsp.vue-ls')
require('lsp.yaml-ls')
require('lsp.elixir-ls')
