--local status_ok, autopairs = pcall(require, "nvim-autopairs")
--if not status_ok then
--  return
--end
--if package.loaded["compe"] then
--  require("nvim-autopairs.completion.compe").setup {
--    map_cr = true, --  map <CR> on insert mode
--    map_complete = true, -- it will auto insert `(` after select function or method item
--  }
--end

